### PR TITLE
Rework the installation procedure

### PR DESCRIPTION
**Pull request by AlCalzone**
As discussed in #64 

This basically does two things:
**ONE:** If the module is being installed inside a `node_modules` folder, it:
1. checks the versions of NodeJS and npm
1. copies everything two directories upwards, e.g. from `/opt/iobroker/node_modules/iobroker/...` to `/opt/iobroker/...`. Files/directories not copied are: `doc`, `img`, `node_modules`, `test`, `wiki` and everything starting with `.`, `package.json`
2. creates a composite `package.json` in the target directory. This includes `scripts`, `engines`, `version` and `dependencies` from this module's `package.json` with three extra deps: `js-controller@stable`, `admin@stable`, `discovery@stable`.
3. Prints a message to the user in green and a fat border with the necessary command to complete the installation

**TWO:** If the module is NOT being installed inside `node_modules` (this happens on the 2nd command):
1. Checks the versions again
1. installs ioBroker as it used to (autostart, user creation and so on). The installation of the three adapter deps is handled by npm itself, so we don't fuck up the dependency tree.

As a bonus, I added an installation script for Linux with some extra fluff. This suppresses the messages to the user and automatically enables the autostart with systemd if that is configured.
unbenannt-1

To test the installation, run `curl -sL https://raw.githubusercontent.com/AlCalzone/ioBroker/install-v2/installer.sh | bash -`

### CODE REVIEW

**Comment by AlCalzone** [comment]
The CI failures come from NodeJS 4, can we finally ditch that or should I fix that too?

**Comment by Apollon77** [comment]
I would say: yes for new installations we can kill nodejs 4. 

@GermanBluefox?!

**Comment by AlCalzone** [comment]
It seems the error comes from `fs-extra`. I could remove that dependency and implement the two missing methods myself - but I'd honestly just get rid of Node 4.

**Comment by GermanBluefox** [comment]
Kill node.js 4

**Comment by AlCalzone** [comment]
The failure comes from Windows/NodeJS 10, where the installation of `request mocha chai` for the tests complains about a missing module - I cannot reproduce this on my local machine.

Everything else is looking good. I'm going to change the paths for the release now, so the following build will most likely fail.

**Comment by AlCalzone** [comment]
This is ready now :)

**Comment by Apollon77** [comment]
How do we need to change testing?

**Comment by AlCalzone** [comment]
Testing is updated to reflect the installation changes - not sure whats happening on Node 10 + Windows though. I cannot reproduce the error on my local machine (also Node 10 + Windows 10).

**Pull request merged**
