### PR TITLE
Raise minimum supported node version to 8.12, test more combinations

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by AlCalzone** [comment]
Linux looks good, the failure is some random Travis-related error.

**Comment by AlCalzone** [comment]
Windows: 
Node 8.12 has no x86/x64 packages for download on AppVeyor yet, this test will succeed in the future
Node 10 has some weird error that only happens on AppVeyor, not locally

**Comment by AlCalzone** [comment]
I think this is good, even with the failures

**Comment by Apollon77** [comment]
reviewed

**Pull request merged**
