### PR TITLE
Fix the check for root/non-root

### PR DESCRIPTION
**Pull request by AlCalzone**
See: https://forum.iobroker.net/viewtopic.php?p=205361#p205361 for details why this is necessary

Also add the current (non-root) user to the iobroker group, so installation of adapters via the console still works (this part is untested).

### CODE REVIEW

**Comment by Apollon77** [comment]
looks good

**Comment by Apollon77** [comment]
testable using master now!

**Comment by AlCalzone** [comment]
Apparently that is not all. I will take another look tomorrow

**Comment by Apollon77** [comment]
k

**Pull request merged**
