### PR TITLE
Create package.json using the installer script, remove old npm install method

### PR DESCRIPTION
**Pull request by AlCalzone**
This makes our installer work on npm7 which no longer allows us to modify package.json during installation.

However, this also removes our preinstall version checks. I'm not sure if we still need them though, since they were put in place to avoid installations on npm < 5.7.1.
I could replace that with a quick check in the script.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Anybody interested in testing?
@Apollon77 @foxriver76

**Comment by Apollon77** [comment]
had no time so far ... after controller

**Comment by foxriver76** [comment]
i can install from your branch, what needs to be tested?

**Comment by AlCalzone** [comment]
Ok let me provide some instructions to test this branch later.

**Comment by AlCalzone** [comment]
Just confirm that the installation works and js-controller starts.

**Comment by AlCalzone** [comment]
So basically: 
1. download the `installer.sh` and `installer_library.sh` from the branch, put them into the same folder
2. replace these lines https://github.com/ioBroker/ioBroker/blob/f6533f60b3086c468fc9ca11e8f61259c844c9a8/installer.sh#L13-L20 with `source ./installer_library.sh`
3. execute `installer.sh`

**Review by foxriver76 — APPROVED** [review]

**Pull request merged**
