### PR TITLE
Usercheck implemented

### PR DESCRIPTION
**Pull request by Grothesk242**
Check if a default user besides 'iobroker' exits and creation of such a user is offered.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Could you please resolve the conflicts?

**Comment by Grothesk242** [comment]
If I only knew how...
Button to resolve is greyed out:
grafik

**Comment by Apollon77** [comment]
Also deleting the DIAG changelog i most likely not intended!!!

**Comment by Apollon77** [comment]
I can manually handle that after my vacation in September

**Comment by Grothesk242** [comment]
*sigh*
I really don't understand how git works... I'm always lost with stashes, commits, pulls, pushes, origins, master, main, forks, branches... I'm always feeling dizzy when trying to land new code somewhere...
10 minutes of coding results in 2 hours figuring out how to commit that stuff. And then it's either more than I wanted to commit, commits from other guys included or the wrong code. No fun...
Sorry

**Comment by Grothesk242** [comment]
See https://github.com/ioBroker/ioBroker/pull/560 instead.

**Pull request closed without merging**
