### PR TITLE
install ioBroker on Raspbian 8/Debian Jessie

### PR DESCRIPTION
**Pull request by keynight**
install ioBroker on Raspbian 8/Debian Jessie with SystemD

### CODE REVIEW

**Comment by keynight** [comment]
ENG: Script for autoinstall ioBroker on Raspbian 8/Debian Jessie
GER: Ein Autoinstall Skript für Raspbian 8/Debian Jessie
RUS: Скрипт устанавливает ioBroker на Raspbian 8/Debian Jessie

**Comment by Apollon77** [comment]
is node 6 also supported for debian jessie? Should we start with node 4or use node 6 ?

**Comment by keynight** [comment]
On node 4.x worked stable, but i not checked with  node 6.x.

**Comment by GermanBluefox** [comment]
Why is the name user is rocker? And not broker or better iobroker? :)

**Comment by GermanBluefox** [comment]
I think node.js 6 must be better tested. Let it at least till April to be 4.

**Comment by GermanBluefox** [comment]
@Apollon77 What do you think is rocker OK as user? I prefer iobroker, but no matter. Otherwise is the script super.

**Comment by Apollon77** [comment]
I also would see a username "near" to the applicationname as usually used for other such cases where software install own useraccounts. so iobroker is better in my eyes

**Comment by Apollon77** [comment]
maybe an option to leave the currently installed nodejs untouched would be good for people that know what they are doing :-)

**Comment by keynight** [comment]
somebody has tried it ? Username is easy: 
ioBroker >> io[Bro]ker = "bro" 
ioBroker >> ioB[roker] = "roker" 
I try to use non standart user for password brute-force complication.

**Comment by GermanBluefox** [comment]
>I try to use non standart user for password brute-force complication.
Nice to know.
thank you. Will merge tonight.

**Pull request merged**
