### PR TITLE
ImgBot Image Optimisation

### PR DESCRIPTION
**Pull request by thost96**
Hi, 

as I forked the repo to add the changes from yesterday I have seen that ImgBot has also found some image optimizations to reduce the image size. So here is the request to add these smaller images ;-) 
Change log is also edited.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hm ... these images are only linked and used here on the Github Readme. They will not be published to NPM.
So if we merge this then there is no need for changelog or version increase in the installer/fixer because it has zero end user relevance.

Can you please change that?

**Comment by thost96** [comment]
> Hm ... these images are only linked and used here on the Github Readme. They will not be published to NPM.
> So if we merge this then there is no need for changelog or version increase in the installer/fixer because it has zero end user relevance.
> 
> Can you please change that?

Changes are taken as requested ;-) I before thought the changelog is a general changelog and not only for the installer, but now this is clear.

**Comment by GermanBluefox** [comment]
@Apollon77 I could not catch it. Can you review?

**Comment by Apollon77** [comment]
I think @AlCalzone is deeoer into it right now

**Pull request merged**
