### PR TITLE
Change to node_6.x

### PR DESCRIPTION
**Pull request by keynight**
Node 4 version is out of date

### CODE REVIEW

**Comment by keynight** [comment]
I have check it with  ARMBIAN 5.38 stable Debian GNU/Linux 9 (stretch) 4.14.18-sunxi. Worked !

**Comment by Apollon77** [comment]
hm ... we need to think exactly ... there are raspbian repos where node 8 is in by default and here this nodejs6 way breaks ...

**Comment by keynight** [comment]
Can you check IOBroker and Node 8 ?

**Comment by GermanBluefox** [comment]
I changed yesterday direct to 8

**Pull request closed without merging**
