### PR TITLE
Add `/sbin` to `PATH` at the start of the script

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes installation on Debian Buster by adding the three known locations of `sbin` to the path if they aren't already there.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Merge?

**Comment by AlCalzone** [comment]
Wait for confirmation from testers in the forum

**Comment by GermanBluefox** [comment]
Do we have the link to forum thread?

**Comment by AlCalzone** [comment]
https://forum.iobroker.net/topic/17159/neue-installationsroutine-und-neue-anleitungen-f%C3%BCr-linux-basierte-systeme/262

Feedback is very limited, but I think we should merge.

**Comment by AlCalzone** [comment]
> adds in worst case the paths twice, but ok :-)

Just for the record, it doesn't. Thats why the first branch in the case statement is there:
```bash
add_to_path() {
	case ":$PATH:" in
		*":$1:"*) :;; # already there
		*) PATH="$1:$PATH";;
	esac
}
```

**Pull request merged**
