### PR TITLE
Third attempt at fixing the FreeBSD installer

### PR DESCRIPTION
**Pull request by AlCalzone**
This time I added a CI test for CirrusCI, which supports testing FreeBSD. We should enable it for this repo (@Apollon77)

Fixes: #194

### CODE REVIEW

**Comment by Apollon77** [comment]
@GermanBluefox needs to activate it

**Comment by AlCalzone** [comment]
BTW, don't merge yet! I still have 1-2 small things to figure out.

**Comment by GermanBluefox** [comment]
I activated cirrus.

**Comment by AlCalzone** [comment]
Thanks! I still have some minor things to work out, then I'll merge.

**Comment by AlCalzone** [comment]
This should be ok now, if the tests are still green

**Pull request merged**
