### PR TITLE
(Linux) Switched from useradd to adduser #174

### PR DESCRIPTION
**Pull request by thost96**
Switched from useradd to adduser to fix issue #174 and also set Suoders File on FreeBSD. There needs also to be defined, which permissions need to be added using the sudoers.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Quota:
```
useradd is native binary compiled with the system. 
But, adduser is a perl script which uses useradd binary in back-end.

adduser is more user friendly and interactive than its back-end useradd. 
There's no difference in features provided.
```

But we must be sure, that perl is installed.

**Comment by AlCalzone** [comment]
I originally raised the issue because some users reported missing homedirs etc. My research back then led me to adduser.
But apparently, adduser is only available on debian, so I'm not sure if that's actually the way forward.

Maybe forcing the dir location like [here](https://unix.stackexchange.com/a/182324) is better?

**Comment by Apollon77** [comment]
If it is as described then the stackoverflow idea might be better

**Comment by GermanBluefox** [comment]
I would close this issue

**Pull request closed without merging**
