### PR TITLE
Autodetect `bash` path to fix `command not found` on FreeBSD

### PR DESCRIPTION
**Pull request by AlCalzone**
As discussed here:
https://forum.iobroker.net/topic/22293/neue-installation-auf-freebsd-freenas-11-2-funktioniert-nicht/

DON'T MERGE YET!

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Will it be finished?

**Comment by AlCalzone** [comment]
We're still working on it, since this needs testing on FreeBSD which I don't have. Unfortunately I didn't have much time in the last few weeks.

**Comment by AlCalzone** [comment]
I will merge this once Travis is through.

**Comment by AlCalzone** [comment]
Merged manually in 78bc737

**Pull request closed without merging**
