### PR TITLE
enable auto-completion for iobroker commands

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #311 

/cc @foxriver76 since you implemented that.

### CODE REVIEW

**Comment by foxriver76** [comment]
LGTM, cannot approve because I am not a collaborator here

**Comment by GermanBluefox** [comment]
Looks really cool. I didn't know that it is possible.

**Comment by foxriver76** [comment]
made a fresh install but the file `iobroker_completions` in `.iobroker` has not been created 
```
-bash: /home/udo/.iobroker/iobroker_completions: Datei oder Verzeichnis nicht gefunden
```

**Comment by AlCalzone** [comment]
Huh I can check later.

**Comment by Apollon77** [comment]
Yes because ou are too fast and this feature will onky exist with js.controller 3.2? Can this be?

**Comment by AlCalzone** [comment]
You're right :D

**Comment by foxriver76** [comment]
Hm the explanation lacks a bit.. the requesting yargs completions will also output `--version` and `--help` pn previous controller versions. Also if the file is not created by the installer the installer should not add the line to bashrc because then everytime opening up a tty you will get an error logged..

**Comment by AlCalzone** [comment]
Good point. I did not consider the possibility that the completions are not created.

**Pull request merged**
