### PR TITLE
update node to version 12

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by AlCalzone** [comment]
LGTM

**Comment by GermanBluefox** [comment]
With this PR we raise the min node.js to 12. Is it OK?

**Comment by Apollon77** [comment]
No problemm,we want to do this with controller 3.x in any case, maybe we should release it "together"? (not needed but would be consistant)

**Comment by AlCalzone** [comment]
Do we actually? We just increase the version that is installed when node was not installed before.

**Pull request merged**
