### PR TITLE
Add info adapter as dependencie

### PR DESCRIPTION
**Pull request by ldittmar81**

### CODE REVIEW

**Comment by Apollon77** [comment]
@ldittmar81 please make shure to add a "stable "tag to the stable version of info adapter ... https://docs.npmjs.com/cli/dist-tag

**Comment by ldittmar81** [comment]
+stable: iobroker.info@1.2.7

done

**Comment by Apollon77** [comment]
Testing restarted

**Comment by Apollon77** [comment]
@AlCalzone Review mostly as "FYI" :-)

**Comment by Apollon77** [comment]
@ldittmar81 do you also want to increase the version so that I can publish faster? :-)

**Comment by ldittmar81** [comment]
Done 😃

**Comment by Apollon77** [comment]
@ldittmar81 should I wait until merge and publish till next version is stable ?!

**Comment by ldittmar81** [comment]
I think we should also publish a new discovery version, so that the Chinese can do the installation completely in Chinese. We should wait till both are stable.

**Comment by ldittmar81** [comment]
+stable: iobroker.info@1.3.7

**Pull request merged**
