### PR TITLE
Add a fix script for existing installations

### LINKED ISSUE #87: Create a script that fixes permissions and autostart and stuff on existing installations
As discussed with @Apollon77 we should create a script that fixes existing installations to a certain degree or brings them up to par with the installations our new installer creates. Let's call it fixmyshit.sh :laughing: 

It should do the following:
- [ ] fix permission errors in `/opt/iobroker`
- [ ] set the permissions like the installer does (with default ACL)
- [ ] create a user iobroker
- [ ] setup autostart with systemd and run iobroker under the iobroker user
- [ ] add permissions for nodejs to access bluetooth, gpio and other ports so we don't need to run adapters with root permissions
- [ ] handle migration from init.d to systemd
- [ ] Install `sudo` if it is not installed
- [ ] Add user `iobroker` to the `sudoers`

Did I forget something?

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes #87

### CODE REVIEW

**Comment by Apollon77** [comment]
Thoughts and Feedback:
* is it good to also have a hard directory here (/opt/iobroker), allow to specify it or run in the iobroker directory? (because existing installations ... may be different then new ones) And if hard coded then output "expected" directory in L39
 Rest is great ...

**Comment by AlCalzone** [comment]
As long as I can remember, ioBroker was installed in /opt/iobroker. I think its fair to assume that it is there. I can add an output where the script is looking for the files.

**Comment by Apollon77** [comment]
Please add FIXER_VERSION=<version> to INSTALLER_INFO file to see the version ... any maybe set date to a current one?!
Should we intrpoduce a FIXER_CHANGELOG.md with the changelog too?

**Comment by AlCalzone** [comment]
Both ideas sound good. Will do that tomorrow

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by AlCalzone** [comment]
Done @Apollon77

**Comment by Apollon77** [comment]
Cool thank you. Will merge and test later. Then put on stable. Then communicate in forum?

**Comment by AlCalzone** [comment]
Sounds good. Did we get any more testers yet?

**Comment by Apollon77** [comment]
I would post it again in telegram, but mainly wold start in "Tester" forum

**Comment by Apollon77** [comment]
PS: I send you some things in Telegram, maybe check those first?

**Pull request merged**
