### PR TITLE
add taobao registry

### PR DESCRIPTION
**Pull request by yaming116**
in china use npm is vary slow

### CODE REVIEW

**Comment by AlCalzone** [comment]
How do you execute the installer with options? Just append them after `bash -` ?

**Comment by Apollon77** [comment]
And then we need another patch for controller to not only nstall via npm or is this just for the initial installation?

**Comment by Apollon77** [comment]
Aahhh I see it is set in npm config ... ok should work basically

**Comment by AlCalzone** [comment]
I have changed the npm registry locally for ioBroker in a side project of mine. That works fine.

But I'm still curious how the installer command line looks like with this @yaming116

**Comment by yaming116** [comment]
like this
```bash
$ curl -fsSL get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh --mirror Aliyun
```

**Comment by AlCalzone** [comment]
So for iobroker it would be
```bash
$ curl -sL https://iobroker.net/install.sh -o install-iobroker.sh
$ bash install-iobroker.sh --mirror Taobao
```
correct?

Alternatively we could think about directly passing the mirror as an env variable
```bash
MIRROR=Taobao curl -sL https://iobroker.net/install.sh | bash -
```

What do you think @Apollon77 ?

**Comment by Apollon77** [comment]
I like the ENV idea ...

**Comment by yaming116** [comment]
Then I am withdrawing this pr resubmission or continue to modify?

**Comment by AlCalzone** [comment]
Please update it to use an env variable.

**Pull request closed without merging**
