### PR TITLE
Remove unnecessary stuff from npm package

### PR DESCRIPTION
**Pull request by AlCalzone**
When this is ok, we should release 2.0.4 (so users don't get the fixer.sh in their installation).

### CODE REVIEW

**Comment by GermanBluefox** [comment]
@Apollon77 Who can verify it?

**Comment by Apollon77** [comment]
@AlCalzone how to continue here? ;-)

**Comment by AlCalzone** [comment]
I need to fix the windows testing.

**Comment by AlCalzone** [comment]
This will be part of #231

**Pull request closed without merging**
